"""add status note to patients

Revision ID: 45e88ccb3647
Revises: d324398a35c0
Create Date: 2026-05-19 13:43:43.785282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e88ccb3647'
down_revision: Union[str, Sequence[str], None] = 'd324398a35c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('status_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'status_note')
    # ### end Alembic commands ###