"""create patients table

Revision ID: d324398a35c0
Revises: f8bd7cf181f4
Create Date: 2026-05-18 10:22:27.779334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd324398a35c0'
down_revision: Union[str, Sequence[str], None] = 'f8bd7cf181f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('preferred_modality', sa.Enum('ONLINE', 'IN_PERSON', 'HYBRID', 'UNSPECIFIED', name='patient_modality'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'ACTIVE', 'FOLLOW_UP', 'INACTIVE', name='patient_status'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('initial_reason', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_index(op.f('ix_patients_full_name'), 'patients', ['full_name'], unique=False)
    op.create_index(op.f('ix_patients_is_active'), 'patients', ['is_active'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_index(op.f('ix_patients_preferred_modality'), 'patients', ['preferred_modality'], unique=False)
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_preferred_modality'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_is_active'), table_name='patients')
    op.drop_index(op.f('ix_patients_full_name'), table_name='patients')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###