"""create employee profiles table

Revision ID: f8bd7cf181f4
Revises: bbb6c66223d3
Create Date: 2026-05-13 16:11:32.047992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bd7cf181f4'
down_revision: Union[str, Sequence[str], None] = 'bbb6c66223d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('neighborhood', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('employment_type', sa.Enum('EMPLOYEE', 'CONTRACTOR', 'EXTERNAL', 'INTERN', name='employment_type'), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('work_schedule', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('nss', sa.String(length=15), nullable=True),
    sa.Column('professional_license', sa.String(length=50), nullable=True),
    sa.Column('ine_document_note', sa.String(length=255), nullable=True),
    sa.Column('curp_document_note', sa.String(length=255), nullable=True),
    sa.Column('rfc_document_note', sa.String(length=255), nullable=True),
    sa.Column('nss_document_note', sa.String(length=255), nullable=True),
    sa.Column('proof_of_address_note', sa.String(length=255), nullable=True),
    sa.Column('professional_license_note', sa.String(length=255), nullable=True),
    sa.Column('contract_document_note', sa.String(length=255), nullable=True),
    sa.Column('documents_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_profiles_curp'), 'employee_profiles', ['curp'], unique=False)
    op.create_index(op.f('ix_employee_profiles_nss'), 'employee_profiles', ['nss'], unique=False)
    op.create_index(op.f('ix_employee_profiles_rfc'), 'employee_profiles', ['rfc'], unique=False)
    op.create_index(op.f('ix_employee_profiles_user_id'), 'employee_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_profiles_user_id'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_rfc'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_nss'), table_name='employee_profiles')
    op.drop_index(op.f('ix_employee_profiles_curp'), table_name='employee_profiles')
    op.drop_table('employee_profiles')
    # ### end Alembic commands ###